<script src="<?=  base_url()?>assets/js/jquery-3.3.1.min.js"></script>
	<script src="<?=  base_url()?>assets/js/bootstrap.min.js"></script>
	<script src="<?=  base_url()?>assets/js/modernizr.js"></script>
	<script src="<?=  base_url()?>assets/js/select2.min.js"></script>
	<script src="<?=  base_url()?>assets/js/jquery.menu-aim.js"></script>
	<script src="<?=  base_url()?>assets/js/jquery-ui.js"></script>
	<script src="<?=  base_url()?>assets/js/jquery.nice-select.min.js"></script>
	<script src="<?=  base_url()?>assets/js/owl.carousel.js"></script>
	<script src="<?=  base_url()?>assets/js/own-menu.js"></script>
	<script src="<?=  base_url()?>assets/js/jquery.bxslider.min.js"></script>
	<script src="<?=  base_url()?>assets/js/jquery.magnific-popup.js"></script>
	<script src="<?=  base_url()?>assets/js/xpedia.js"></script>